version: "3.9"
services:
  as:
    build: ./AS
    container_name: as
    ports:
      - "53533:53533/udp"
    networks: [dnsnet]

  fs:
    build: ./FS
    container_name: fs
    ports:
      - "9090:9090"
    depends_on: [as]
    networks: [dnsnet]

  us:
    build: ./US
    container_name: us
    ports:
      - "8080:8080"
    depends_on: [as, fs]
    networks: [dnsnet]

networks:
  dnsnet:
    driver: bridge
